UI Development
team4909/The-Green-Alliance pull request #3
Opened 2019-01-13 18:28 UTC by ShashJar

Makes all of adjustments from last year's scouting app to this year's. UI has been changed to include all metrics currently identified for each of Match Metadata, Autonomous (Sandstorm Period), TeleOp Period, and Endgame. UI has been viewed and tested, all is functional. Additional changes yet to be made include using jquery to separate the different sections of the scouting app into tabs so that the scout can switch between them at any point in the match, as well as adding the metric of which side a team scores on during autonomous.

2019-01-13 18:40 UTC, roshanr10 requested changes
Separate jQuery Tabs Please

2019-01-14 23:20 UTC, ShashJar commented
jQuery tabs will be added, merge for now?

2019-01-14 23:28 UTC, roshanr10 commented
UI goes hand in hand w/ the tabs, see my comments in issue #2... should be easy enough but I'd like to see how it looks when simulated for the screen resolution before we finalize this

2019-01-18 00:35 UTC, ShashJar commented
@roshanr10  Please review the UI, let me know with any suggestions for changes. Tabs are finalized, overflow has been set to scroll, tabs have not yet been colored/styled. If no issues, I'm good with merging now.

2019-01-18 19:40 UTC, roshanr10 commented
I'd like to wrap up the tab styling today before we merge into master.

2019-02-26 03:48 UTC, roshanr10 commented on app/www/js/main.js
> +    // TODO: Clear Fields
@ShashJar can you implement this? should be fairly straightforward, numeric fields default to 0, checkboxes to false, and text fields to ""

2019-02-26 22:34 UTC, roshanr10 commented
Pending for Basic Web Usage:
- [ ] Clear on Submit @ShashJar 
- [ ] basic output view (match and average) @roshanr10 
- [ ] off-line data @roshanr10 
- [ ] disable arrows on number input (https://www.thatstevensguy.com/programming/disable-arrows-on-number-inputs/) @roshanr10

2019-02-27 03:50 UTC, roshanr10 commented
@shashjar sorry buddy those changes won’t work, did you test..?

See http://api.jquery.com/val/#val2 for more help on setting textbox values in Jquery and https://stackoverflow.com/a/17420580 for the checkbox equivalent.

2019-02-27 16:45 UTC, roshanr10 approved these changes

2019-02-27 16:45 UTC, merged